/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_duke_cs_tpie_DoublePriorityQueue */

#ifndef _Included_edu_duke_cs_tpie_DoublePriorityQueue
#define _Included_edu_duke_cs_tpie_DoublePriorityQueue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_duke_cs_tpie_DoublePriorityQueue
 * Method:    create
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_edu_duke_cs_tpie_DoublePriorityQueue_create
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_duke_cs_tpie_DoublePriorityQueue
 * Method:    cleanup
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_duke_cs_tpie_DoublePriorityQueue_cleanup
  (JNIEnv *, jclass, jlong);

/*
 * Class:     edu_duke_cs_tpie_DoublePriorityQueue
 * Method:    push
 * Signature: (JLedu/duke/cs/tpie/DoublePriorityQueue/Entry;)V
 */
JNIEXPORT void JNICALL Java_edu_duke_cs_tpie_DoublePriorityQueue_push
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     edu_duke_cs_tpie_DoublePriorityQueue
 * Method:    top
 * Signature: (JLedu/duke/cs/tpie/DoublePriorityQueue;)Ledu/duke/cs/tpie/DoublePriorityQueue/Entry;
 */
JNIEXPORT jobject JNICALL Java_edu_duke_cs_tpie_DoublePriorityQueue_top
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     edu_duke_cs_tpie_DoublePriorityQueue
 * Method:    pop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_duke_cs_tpie_DoublePriorityQueue_pop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     edu_duke_cs_tpie_DoublePriorityQueue
 * Method:    size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_edu_duke_cs_tpie_DoublePriorityQueue_size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     edu_duke_cs_tpie_DoublePriorityQueue
 * Method:    empty
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_duke_cs_tpie_DoublePriorityQueue_empty
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_duke_cs_tpie_DoublePriorityQueue_Entry */

#ifndef _Included_edu_duke_cs_tpie_DoublePriorityQueue_Entry
#define _Included_edu_duke_cs_tpie_DoublePriorityQueue_Entry
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
