/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_duke_cs_tpie_FIFOQueue */

#ifndef _Included_edu_duke_cs_tpie_FIFOQueue
#define _Included_edu_duke_cs_tpie_FIFOQueue
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
