/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_duke_cs_tpie_TPIE */

#ifndef _Included_edu_duke_cs_tpie_TPIE
#define _Included_edu_duke_cs_tpie_TPIE
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_duke_cs_tpie_TPIE
 * Method:    init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_duke_cs_tpie_TPIE_init
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_duke_cs_tpie_TPIE
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_duke_cs_tpie_TPIE_cleanup
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
